version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./deployment/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../..:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    volumes:
      - orderflow_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env

volumes:
  orderflow_postgres_data: {}
